Code review ver 1
AleksandrHexlet/travelBook.github.io pull request #1
Opened 2020-03-25 15:32 UTC by AleksandrHexlet

1) Установлен вебпак
2) Установлены необходимые для работы плагины.
3) Созданы три сборки.
4) Изменена структура файлов в папке.
5) Код разбит на модули
6) Настроены импорты-экспорты
7)Настроено хеширование и hot-reload

2020-03-25 15:44 UTC, AleksandrHexlet commented
last check before review

2020-03-25 18:16 UTC, zlocate commented on src/index.js
> +  baseUrl: NODE_ENV === 'development'
Отлично!

2020-03-25 18:17 UTC, zlocate commented on .gitignore
> +node_modules
**Можно лучше**: Расширить список правил, например добавить .DS_Store

2020-03-25 18:17 UTC, zlocate commented on package.json
> +  "author": "",
**Можно лучше**: Указать авторство :)

2020-03-25 18:18 UTC, zlocate commented on package.json
> +    "lodash": "^4.17.15",
**Можно лучше**: данный модуль не используется в проекте

2020-03-25 18:19 UTC, zlocate commented on package.json
> +    "path": "^0.12.7",
**Можно лучше** в актуальных версиях NodeJS данный модуль встроен и не требует дополнительной установки

2020-03-25 18:20 UTC, zlocate commented on webpack.config.js
> +execFile (pngquant, ['-o', 'output.png', 'input.png'], err => {
Отлично: минификация png позволяет ускорить загрузку ресурса не потеряв в качестве графики. Круто!

2020-03-25 18:22 UTC, zlocate commented on README.md
>  This site allows you to view photos, the name of the photo.The user can add a photo by clicking on the "+"button. Each photo has the following functionality: like, delete, and zoom in.    Technologie
**Нужно исправить**: Необходимо добавить инструкцию по разворачиванию проекта

2020-03-25 18:23 UTC, zlocate commented on src/script/scripts.js
> +/*
**Можно лучше** просьба удалять комментарии от прошлых ревью.

2020-03-25 18:24 UTC, zlocate commented
**Можно лучше**: Файл, расположенный в /src/script/script.js не используется. Можно удалить :)

2020-03-25 18:25 UTC, zlocate commented on src/index.html
> +      <div class="place-card">
**Можно лучше** постарайтесь избежать закомментированного кода в финальной версии проекта

2020-03-25 18:27 UTC, zlocate commented
При изменении данных профиля в консоль сыплет `Обновлённые данные: [object Object]`.
Вероятно вы хотели вывести поля из данного объекта

2020-03-25 18:27 UTC, zlocate commented
**Можно лучше** в консоль сыплется отладочный вывод.

2020-03-25 18:32 UTC, zlocate requested changes
Добрый вечер. 
Благодарю за аккуратность при выполнении задания.

После исправления данного аспекта работа будет засчитана:
**Нужно исправить:** Необходимо добавить инструкцию по разворачиванию проекта

2020-03-26 18:11 UTC, AleksandrHexlet commented
Добрый день! 
Спасибо за ревью !

По выполненным действиям на основе ваших рекомендаций : 
1) Консоль почистил;
2) Лишний закомментированный и отладочный код убрал;
3) Не используемый файл по адресу : /src/script/script.js удалил
4) Path and Lodash оставил; 
    В коде используются шаблоны Lodash, если уберу плагин шаблоны будут работать ?
5).DS_Store добавил в .gitignore
6) Авторство указал;
7) Инструкцию по разворачиванию проекта написал и добавил в README.

P.S. Старался выполнить всё рекомендации, если что-то пропустил,тогда напишите пожалуйста 
    и я поправлю.

2020-03-27 11:02 UTC, zlocate commented on webpack.config.js
> +const imagemin = require('imagemin');
**Можно лучше** убедитесь что данный модуль действительно используется.

2020-03-27 11:02 UTC, zlocate commented on webpack.config.js
> +const imageminPngquant = require('imagemin-pngquant');
**Можно лучше** убедитесь что данный модуль действительно используется.

2020-03-27 11:02 UTC, zlocate commented on webpack.config.js
> +const pngquantExec = execFile(pngquant, ['-o', 'output.png', 'input.png']);
**Можно лучше** убедитесь что данный фрагмент действительно используется.

2020-03-27 11:22 UTC, zlocate commented
Добрый день. Благодарю за оперативное внесение изменений.
Осталась проблема, требующая исправления:
**Нужно исправить** в результирующем билде, в т.ч размещенном на Github Pages кнопка простановки лайка отображается некорректно:
Скриншот https://prnt.sc/rnr2yw

Рекомендации:
**Можно лучше** клик по кнопке удаления не приводит к отправке соответствующего запроса к API. Это точно то поведение, которое вы ожидали?

**Можно лучше**: укажите авторство в package.json.
Скриншот текущей версии - https://prnt.sc/rnra08

**Можно лучше**: используйте git-теги для версионирования.

2020-03-28 10:44 UTC, AleksandrHexlet commented
Добрый день!
По порядку:
1) Like  починил. Новый код запушил в dev  и  в gh-pages. После открыл ссылку и проверил---работает.
2) Сейчас при клике на корзину карточка удаляется.Если там что-то не так,я бы хотел поправить. Объясните пожалуйста более развернуто.

3) Авторство указал ( прошлый раз тоже указывал, но видимо не в той ветке.Получилось,что в отчёте написал не правду. Sorry.Буду внимательнее).
4) Версии проставил.

Хорошего вам дня !

2020-03-29 06:51 UTC, zlocate commented
Добрый день. Отлично!
1. Принято.
2. Просмотрел задание для вашего потока там реализация методов API для удаления карточки является доп заданием и достаточно просто визуально ее убирать. Принимается :)
3. Принято. Ничего страшного :)
4. Отлично!

Работа зачтена. Желаю успехов в дальнейшем обучении на курсе!

2020-03-30 14:40 UTC, merged